import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";
import type { ChatMessage, Mode } from "../types";

const DATE = () => new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

// ─── Markdown export ──────────────────────────────────────────────────────────

export function exportMarkdown(text: string, mode: Mode, title?: string): void {
  const content = `# ${title || `StudentMind — ${mode}`}\n_Exported on ${DATE()}_\n\n---\n\n${text}`;
  downloadBlob(content, `studentmind-${slug(mode)}.md`, "text/markdown");
}

// ─── Plain text export ────────────────────────────────────────────────────────

export function exportText(text: string, mode: Mode): void {
  const stripped = text
    .replace(/#{1,6}\s+/g, "")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/`{1,3}[^`]*`{1,3}/g, (m) => m.replace(/`/g, ""))
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/^\|.*\|$/gm, (row) => row.replace(/\|/g, " ").replace(/\s{2,}/g, " ").trim())
    .replace(/^[-*]\s+/gm, "• ")
    .replace(/^\d+\.\s+/gm, (m) => m);
  const content = `StudentMind — ${mode}\nExported on ${DATE()}\n\n${stripped}`;
  downloadBlob(content, `studentmind-${slug(mode)}.txt`, "text/plain");
}

// ─── PDF export ───────────────────────────────────────────────────────────────

export async function exportPDF(text: string, mode: Mode, title?: string): Promise<void> {
  // Dynamically import html2pdf to avoid SSR issues
  const html2pdf = (await import("html2pdf.js")).default;

  const html = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 700px; margin: 0 auto; color: #1a1a2e; padding: 40px;">
      <div style="border-bottom: 3px solid #10b981; padding-bottom: 20px; margin-bottom: 30px;">
        <h1 style="font-size: 24px; font-weight: 700; color: #0f172a; margin: 0 0 6px 0;">
          ${title || `StudentMind — ${mode}`}
        </h1>
        <p style="font-size: 12px; color: #64748b; margin: 0;">Exported on ${DATE()}</p>
      </div>
      <div style="line-height: 1.7; font-size: 13.5px;">
        ${markdownToHtml(text)}
      </div>
      <div style="margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; text-align: center;">
        Generated by StudentMind AI — studentmind.app
      </div>
    </div>`;

  const el = document.createElement("div");
  el.innerHTML = html;
  document.body.appendChild(el);

  await html2pdf().set({
    margin: [10, 10, 10, 10],
    filename: `studentmind-${slug(mode)}.pdf`,
    image: { type: "jpeg", quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true },
    jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
  }).from(el).save();

  document.body.removeChild(el);
}

// ─── DOCX export ──────────────────────────────────────────────────────────────

export async function exportDocx(text: string, mode: Mode, title?: string): Promise<void> {
  const lines = text.split("\n");
  const children: Paragraph[] = [];

  // Title
  children.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun({ text: title || `StudentMind — ${mode}`, bold: true, size: 36, color: "0F172A" })],
      spacing: { after: 160 },
    }),
    new Paragraph({
      children: [new TextRun({ text: `Exported on ${DATE()}`, size: 20, color: "64748B", italics: true })],
      spacing: { after: 400 },
    })
  );

  // Parse lines
  for (const line of lines) {
    if (!line.trim()) {
      children.push(new Paragraph({ children: [] }));
      continue;
    }

    if (line.startsWith("### ")) {
      children.push(new Paragraph({
        heading: HeadingLevel.HEADING_3,
        children: [new TextRun({ text: line.slice(4), bold: true, size: 26, color: "0F172A" })],
        spacing: { before: 200, after: 100 },
      }));
    } else if (line.startsWith("## ")) {
      children.push(new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: line.slice(3), bold: true, size: 30, color: "0F172A" })],
        spacing: { before: 300, after: 160 },
      }));
    } else if (line.startsWith("# ")) {
      children.push(new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [new TextRun({ text: line.slice(2), bold: true, size: 34, color: "0F172A" })],
        spacing: { before: 400, after: 200 },
      }));
    } else if (line.startsWith("- ") || line.startsWith("* ")) {
      children.push(new Paragraph({
        bullet: { level: 0 },
        children: parseInline(line.slice(2)),
        spacing: { after: 80 },
      }));
    } else if (/^\d+\.\s/.test(line)) {
      children.push(new Paragraph({
        numbering: { reference: "default-numbering", level: 0 },
        children: parseInline(line.replace(/^\d+\.\s/, "")),
        spacing: { after: 80 },
      }));
    } else if (line.startsWith("|")) {
      // Skip table lines in DOCX (too complex, export as plain row)
      const cells = line.split("|").filter(c => c.trim() && !c.match(/^[\s-]+$/));
      if (cells.length > 0) {
        children.push(new Paragraph({
          children: [new TextRun({ text: cells.map(c => c.trim()).join("  •  "), size: 22, color: "374151" })],
          spacing: { after: 80 },
        }));
      }
    } else if (line.startsWith("```")) {
      // Skip code fence markers
    } else {
      children.push(new Paragraph({
        children: parseInline(line),
        spacing: { after: 120 },
      }));
    }
  }

  const doc = new Document({
    numbering: {
      config: [{
        reference: "default-numbering",
        levels: [{ level: 0, format: "decimal" as any, text: "%1.", alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 360 } } } }],
      }],
    },
    sections: [{
      properties: {},
      children,
    }],
  });

  const blob = await Packer.toBlob(doc);
  downloadBlobObj(blob, `studentmind-${slug(mode)}.docx`);
}

// ─── Full conversation export ─────────────────────────────────────────────────

export async function exportConversation(
  messages: ChatMessage[],
  format: "md" | "txt" | "pdf" | "docx",
  provider: string,
  model: string
): Promise<void> {
  const date = DATE();
  let content = "";

  for (const msg of messages) {
    if (msg.id === "welcome") continue;
    const sender = msg.sender === "user" ? "**You**" : "**StudentMind**";
    const time = new Date(msg.timestamp).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" });
    content += `${sender} _(${time})_\n\n${msg.text}\n\n---\n\n`;
  }

  const title = `StudentMind Conversation`;
  const header = `# ${title}\n_${date} · ${provider} / ${model}_\n\n---\n\n`;
  const full = header + content;

  if (format === "md") downloadBlob(full, `studentmind-conversation.md`, "text/markdown");
  else if (format === "txt") downloadBlob(full.replace(/[*_#`]/g, ""), `studentmind-conversation.txt`, "text/plain");
  else if (format === "pdf") await exportPDF(full, "Chat" as Mode, title);
  else if (format === "docx") await exportDocx(content, "Chat" as Mode, title);
}

// ─── Share ────────────────────────────────────────────────────────────────────

export function shareAsMarkdown(messages: ChatMessage[], provider: string, model: string): string {
  let md = `# StudentMind Conversation\n_${DATE()} · ${provider} / ${model}_\n\n`;
  for (const msg of messages) {
    if (msg.id === "welcome") continue;
    const who = msg.sender === "user" ? "👤 You" : "🤖 StudentMind";
    md += `### ${who}\n${msg.text}\n\n`;
  }
  return md;
}

export function generateShareUrl(messages: ChatMessage[]): string {
  // Encode only the last 10 messages to keep URL reasonable
  const subset = messages.filter(m => m.id !== "welcome").slice(-10);
  const compressed = subset.map(m => ({ s: m.sender[0], t: m.text.slice(0, 500) }));
  const encoded = btoa(encodeURIComponent(JSON.stringify(compressed)));
  return `${window.location.origin}${window.location.pathname}#share=${encoded}`;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function slug(mode: string): string {
  return mode.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
}

function downloadBlob(content: string, filename: string, type: string): void {
  const blob = new Blob([content], { type });
  downloadBlobObj(blob, filename);
}

function downloadBlobObj(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function parseInline(text: string): TextRun[] {
  const runs: TextRun[] = [];
  // Simple bold/italic/code parsing
  const parts = text.split(/(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`)/);
  for (const part of parts) {
    if (part.startsWith("**") && part.endsWith("**")) {
      runs.push(new TextRun({ text: part.slice(2, -2), bold: true, size: 24 }));
    } else if (part.startsWith("*") && part.endsWith("*")) {
      runs.push(new TextRun({ text: part.slice(1, -1), italics: true, size: 24 }));
    } else if (part.startsWith("`") && part.endsWith("`")) {
      runs.push(new TextRun({ text: part.slice(1, -1), font: "Courier New", size: 22, color: "059669" }));
    } else if (part) {
      runs.push(new TextRun({ text: part, size: 24 }));
    }
  }
  return runs.length ? runs : [new TextRun({ text, size: 24 })];
}

function markdownToHtml(md: string): string {
  return md
    .replace(/^### (.+)$/gm, "<h3 style='font-size:15px;color:#0f172a;margin:20px 0 8px'>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2 style='font-size:18px;color:#0f172a;margin:24px 0 10px'>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1 style='font-size:22px;color:#0f172a;margin:28px 0 12px'>$1</h1>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/`([^`]+)`/g, "<code style='background:#f1f5f9;padding:2px 6px;border-radius:4px;font-size:12px;color:#0f766e'>$1</code>")
    .replace(/^```[\w]*\n([\s\S]*?)```$/gm, "<pre style='background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px;font-size:12px;overflow:auto'>$1</pre>")
    .replace(/^\| (.+) \|$/gm, (row) => {
      const cells = row.split("|").filter(c => c.trim());
      return `<div style='display:flex;gap:8px;border-bottom:1px solid #e2e8f0;padding:6px 0'>${cells.map(c => `<span style='flex:1;font-size:12px'>${c.trim()}</span>`).join("")}</div>`;
    })
    .replace(/^[-*] (.+)$/gm, "<div style='margin:4px 0 4px 16px'>• $1</div>")
    .replace(/^\d+\. (.+)$/gm, (_, item, offset, str) => `<div style='margin:4px 0 4px 16px'>${item}</div>`)
    .replace(/^---$/gm, "<hr style='border:none;border-top:1px solid #e2e8f0;margin:20px 0'>")
    .replace(/\n\n/g, "<br><br>")
    .replace(/\n/g, "<br>");
}
